# Generated by Django 5.1.1 on 2026-06-17 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('subscription', '0004_remove_subscriptionpackage_package_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanExamAccessLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_access_count', models.PositiveIntegerField()),
                ('limit_type', models.CharField(choices=[('daily', 'Daily'), ('total', 'Total')], default='total', max_length=10)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlanPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('weekly', 'সাপ্তাহিক'), ('biweekly', 'পাক্ষিক'), ('monthly', 'মাসিক'), ('quarterly', 'ত্রৈমাসিক'), ('halfyearly', 'ষাণ্মাসিক')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlanTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('plus', 'Plus'), ('premium', 'Premium')], max_length=50, unique=True)),
                ('ad_free', models.BooleanField(default=False)),
                ('free_model_test', models.BooleanField(default=True)),
                ('paid_model_test', models.BooleanField(default=True)),
                ('daily_previous_year_questions', models.PositiveIntegerField(default=0)),
                ('upcoming_special_model_tests', models.PositiveIntegerField(default=0)),
                ('prize_winning_special_exam', models.BooleanField(default=False)),
                ('daily_live_exam_room_access', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserExamAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField()),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='package',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='payment',
        ),
        migrations.DeleteModel(
            name='PaymentPlan',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subscriptionanalytics',
            name='package',
        ),
        migrations.RemoveField(
            model_name='subscriptionhistory',
            name='package',
        ),
        migrations.RemoveField(
            model_name='subscriptionhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usagetracking',
            name='package',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='package',
        ),
        migrations.RemoveField(
            model_name='usagetracking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='auto_renew',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='status',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplanprice',
            name='plan_tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='subscription.subscriptionplantier'),
        ),
        migrations.AddField(
            model_name='planexamaccesslimit',
            name='plan_tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_access_limits', to='subscription.subscriptionplantier'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.subscriptionplantier'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
        migrations.DeleteModel(
            name='SubscriptionAnalytics',
        ),
        migrations.DeleteModel(
            name='SubscriptionHistory',
        ),
        migrations.DeleteModel(
            name='SubscriptionPackage',
        ),
        migrations.DeleteModel(
            name='UsageTracking',
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionplanprice',
            unique_together={('plan_tier', 'duration')},
        ),
        migrations.AlterUniqueTogether(
            name='planexamaccesslimit',
            unique_together={('plan_tier', 'content_type')},
        ),
    ]
