# Generated by Django 5.2.11 on 2026-02-08 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0002_department_examtype_organization_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('official_link', models.URLField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='govt_job_pdfs/')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='government_jobs', to='quiz.department')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='government_jobs', to='quiz.organization')),
                ('positions', models.ManyToManyField(blank=True, related_name='government_jobs', to='quiz.position')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='notices/')),
                ('link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('government_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='govt_jobs.governmentjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
