# Generated by Django 5.1.1 on 2026-09-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_add_question_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroup',
            name='reviewed',
            field=models.BooleanField(default=True),
        ),
    ]
