# Generated by Django 5.2.11 on 2026-02-09 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0002_department_examtype_organization_position_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='passage_images/')),
                ('is_image', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.subject')),
            ],
        ),
        migrations.CreateModel(
            name='RootExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('exam_mode', models.CharField(blank=True, choices=[('mcq', 'MCQ'), ('written', 'Written'), ('both', 'Both')], max_length=10, null=True)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_root_exams', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_exams', to='quiz.department')),
                ('exam_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_exams', to='quiz.examtype')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_exams', to='quiz.organization')),
                ('past_exam', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_exam', to='quiz.pastexam')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_exams', to='quiz.position')),
                ('subjects', models.ManyToManyField(related_name='root_exams', to='quiz.subject')),
            ],
        ),
        migrations.CreateModel(
            name='WrittenExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.PositiveIntegerField(blank=True, null=True)),
                ('total_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('root_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_exams', to='written_exam.rootexam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.subject')),
            ],
        ),
        migrations.CreateModel(
            name='WrittenQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='written_questions/')),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('answer_image', models.ImageField(blank=True, null=True, upload_to='written_questions/answers/')),
                ('explanation_text', models.TextField(blank=True, help_text='Detailed text explanation for the question.', null=True)),
                ('explanation_image', models.ImageField(blank=True, help_text='Image-based explanation for the question.', null=True, upload_to='written_questions/explanations/')),
                ('is_image', models.BooleanField(default=False)),
                ('question_number', models.PositiveIntegerField()),
                ('has_sub_questions', models.BooleanField(default=False)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_questions', to='written_exam.passage')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.subject')),
                ('written_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='written_exam.writtenexam')),
            ],
        ),
        migrations.CreateModel(
            name='SubWrittenQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='sub_written_questions/')),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('answer_image', models.ImageField(blank=True, null=True, upload_to='sub_written_questions/answers/')),
                ('explanation_text', models.TextField(blank=True, help_text='Detailed text explanation for the sub-question.', null=True)),
                ('explanation_image', models.ImageField(blank=True, help_text='Image-based explanation for the sub-question.', null=True, upload_to='sub_written_questions/explanations/')),
                ('is_image', models.BooleanField(default=False)),
                ('number', models.PositiveIntegerField()),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_questions', to='written_exam.writtenquestion')),
            ],
        ),
    ]
