# Generated by Django 5.2.11 on 2026-02-08 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartOfSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_definition', models.TextField()),
                ('usage_note', models.TextField(blank=True)),
                ('synonyms', models.TextField(blank=True, help_text='Comma separated synonyms (e.g. add, connect, join)')),
                ('antonyms', models.TextField(blank=True, help_text='Comma separated antonyms (e.g. remove, subtract)')),
            ],
        ),
        migrations.CreateModel(
            name='ExampleSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('sense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='language_center.sense')),
            ],
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition_text', models.TextField()),
                ('sense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='language_center.sense')),
            ],
        ),
        migrations.CreateModel(
            name='BanglaMeaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.TextField()),
                ('note', models.CharField(blank=True, help_text='formal / informal / literal / figurative', max_length=100)),
                ('sense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bangla_meanings', to='language_center.sense')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, max_length=100)),
                ('phonetic_uk', models.CharField(blank=True, max_length=100)),
                ('phonetic_us', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='language_center.language')),
                ('part_of_speech', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='language_center.partofspeech')),
            ],
            options={
                'ordering': ['text'],
                'unique_together': {('language', 'text', 'part_of_speech')},
            },
        ),
        migrations.AddField(
            model_name='sense',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senses', to='language_center.word'),
        ),
        migrations.CreateModel(
            name='WordForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=50)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='language_center.word')),
            ],
        ),
        migrations.CreateModel(
            name='ExampleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translated_text', models.TextField()),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='language_center.examplesentence')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_center.language')),
            ],
            options={
                'unique_together': {('example', 'language')},
            },
        ),
        migrations.CreateModel(
            name='DefinitionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translated_text', models.TextField()),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='language_center.definition')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_center.language')),
            ],
            options={
                'unique_together': {('definition', 'language')},
            },
        ),
    ]
